name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Build Docker image
      run: docker build . -t my-portfolio-notification-service

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: eu-north-1
        AWS_ACCOUNT_ID: 816069136450
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --ppj555 AWS --Mac@5807-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Push Docker image to Amazon ECR
      env:
        AWS_REGION: eu-north-1
        AWS_ACCOUNT_ID: 816069136450
      run: |
        docker tag portfolio/my-portfolio:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portfolio/my-portfolio:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/portfolio/my-portfolio:latest