name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build . -t my-portfolio-notification-service

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIA34AMC2BBCV77MF6Q
        aws-secret-access-key: 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
        aws-region: eu-north-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      env:
        AWS_REGION: eu-north-1
        AWS_ACCOUNT_ID: 816069136450

    - name: Push Docker image to Amazon ECR
      run: |
        docker my-portfolio-notification-service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-portfolio-notification-service:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-portfolio-notification-service:latest
      env:
        AWS_REGION: eu-north-1
        AWS_ACCOUNT_ID: 816069136450
