name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Build Docker image
      run: docker build . -t my-portfolio-notification-service:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIA34AMC2BBCV77MF6Q
        aws-secret-access-key: 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
        aws-region: eu-north-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 816069136450.dkr.ecr.eu-north-1.amazonaws.com

    - name: Tag Docker image
      run: docker tag my-portfolio-notification-service:latest 816069136450.dkr.ecr.eu-north-1.amazonaws.com/portfolio/my-portfolio:latest

    - name: Push Docker image to Amazon ECR
      run: docker push 816069136450.dkr.ecr.eu-north-1.amazonaws.com/portfolio/my-portfolio

    - name: Deploy to EC2
      run: |
        aws ec2 describe-instances --filters "Name=tag:Name,Values=my-ec2-instance" --query "Reservations[*].Instances[*].PublicIpAddress" --output text > ec2_ip.txt
        EC2_IP=$(cat ec2_ip.txt)
        ssh -o StrictHostKeyChecking=no -i portfolio.pem ec2-user@$EC2_IP << 'EOF'
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 816069136450.dkr.ecr.eu-north-1.amazonaws.com
          docker pull 816069136450.dkr.ecr.eu-north-1.amazonaws.com/portfolio/my-portfolio:latest
          docker stop my-portfolio-notification-service || true
          docker rm my-portfolio-notification-service || true
          docker run -d -p 6000:6000 --name my-portfolio-notification-service:latest 816069136450.dkr.ecr.eu-north-1.amazonaws.com/portfolio/my-portfolio:latest
        EOF